### ISSUE TITLE
codemeta hook should ignore "fileSize" field

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#84] opened 2019-12-27 20:21 UTC
When using this hook, it fails on every commit for me because the "fileSize" field changes during every hook run

```sh
diff --git a/codemeta.json b/codemeta.json
index 6ed3510..ddc28bb 100644
--- a/codemeta.json
+++ b/codemeta.json
@@ -212,7 +212,7 @@
   ],
   "releaseNotes": "https://github.com/pat-s/circle/blob/master/NEWS.md",
   "readme": "https://github.com/pat-s/circle/blob/master/README.md",
-  "fileSize": "16.507KB",
+  "fileSize": "16.508KB",
   "contIntegration": [
     "https://travis-ci.org/pat-s/circle3",
     "https://circleci.com/gh/pat-s/circle",
```

which makes it impossible for me to run this hook successfully.

**Comment by lorenzwalthert** [comment] 2019-12-27 21:36
Can you help @maelle?

**Comment by maelle** [comment] 2019-12-29 12:00
I can't help before Jan the 8th. I am sorry, it definitely seems wrong since the hook shouldn't react to changes in codemeta.json, it should only fail if DESCRIPTION changed.

**Comment by maelle** [comment] 2019-12-29 12:07
@pat-s can you write the steps leading to failure to make it easier for me to investigate when i am back? For instance I do not understand how the hook can change a field? (I.e. why the fileSize argument changes during the hook run)

For reference https://github.com/lorenzwalthert/precommit/blob/master/inst/bin/codemeta-description-updated

**Comment by pat-s** [comment] 2019-12-29 16:55
@maelle No rush :)

I just added the hook to my repo `pat-s/circle` and the hook modified `codemeta.json` on every run. Idk why :)

You should be able to reproduce this by checking out this repo and adding the hook (I commented it for now).

**Comment by lorenzwalthert** [comment] 2019-12-29 17:14
@pat-s I can't reproduce the behavior. Here is what I did:

- modify DESCRIPTION.
- try to commit (failed).
- run  `codemetar::write_codemeta()` (success with changing codemeta.json).
- `git add .`, and the commit (success).

Just to make sure we are on the same page: The codemetar hook is a hook without side effects and when it fails the first time, it will fail every consecutive time unless  `codemetar::write_codemeta()` is ran (and the changes are staged). This is unlike many other hooks such as the styler hook. It will (because it is idempotent) fail maximal once, change files, and succeed the next time, assuming you staged the changes it created during the first run. Same with the spelling hook, because it will simply add all words it does not know to the WORDLIST and the user must manually remove them if they were really spelling mistakes.

Does this clarify the problem? Maybe when implementing #63, we should add a column *side effects* to make sure people can easily see which hooks change stuff and which hooks just check stuff and want the user to fix a problem before re-attempting.

**Comment by pat-s** [comment] 2019-12-29 17:25
> and when it fails the first time, it will fail every consecutive time unless codemetar::write_codemeta() is ran (and the changes are staged).

Yes I did so. Run `write_codemeta()`, staged both DESC and codemeta.json and then I am getting

![Screenshot 2019-12-29 at 18 22 13](https://user-images.githubusercontent.com/8430564/71560281-3f964700-2a68-11ea-9532-d39ebbe4c36f.png)

Running `write_codemeta()` again will again change the "fileSize" field and the hook will fail. This goes on infinitely.

**Comment by maelle** [comment] 2020-01-08 13:07
I have just re-installed the latest precommit version and cannot reproduce the bug.

1. `precommit::use_precommit()`
2. uncommented the codemeta hook.
3. modified DESCRIPTION
4. tried to commit, which failed because of the hook
5. updated codemeta.json
6. tried to commit, which worked

I'm using codemetar dev version, but even codemetar CRAN version shouldn't modify DESCRIPTION.

@pat-s can you provide a bit more info on the steps you followed? sorry.

**Comment by maelle** [comment] 2020-01-08 13:08
I did this in another repo, I'll clone circle now.

**Comment by lorenzwalthert** [comment] 2020-01-08 13:10
@pat-s maybe try empty the pre-commit cache with `pre-commit clean` in the terminal? Also I had problems with the RStudio git tab a few rare times when using pre-commit.

**Comment by maelle** [comment] 2020-01-08 13:30
Ok so when I use the hook in circle I get problem if the order is not

```

    -   id: codemeta-description-updated
    -   id: use-tidy-description
```

because use-tidy-description modifies DESCRIPTION. :-)

But with that order things seem fine to me (I edited DESCRIPTION, it failed, then I updated codemeta.json and the commit worked)

**Comment by maelle** [comment] 2020-01-08 13:33
(I use the RStudio commit tab).

**Comment by pat-s** [comment] 2020-01-08 15:11
Thanks @maelle, works now for me! Makes sense that the order of the hooks has an influence here. Not sure how easy it is to account for this in the package. Maybe just make a note in the README? (Or maybe one can do fancy upstream stuff like define dependencies between hooks)

If you move this hook to be run as the first one in the template, it should not appear very often (I guess users won't change the order of these two hooks if they are set once).

**Comment by maelle** [comment] 2020-01-08 15:23
@pat-s awesome!

@lorenzwalthert I can make a PR depending on your decision.

**Comment by lorenzwalthert** [comment] 2020-01-08 15:26
Yes we should adapt the documentation and the order of the hooks.

**Comment by lorenzwalthert** [comment] 2020-01-08 15:31
Thanks for resolving @maelle. Yes we should adapt the documentation and the order of the hooks. @maelle you can move the hook all the way up to the top in the section `#  R package development` in the config file, comment it out and add `# must be listed above use-tidy-description when both are used to work properly` (or similar)?
Also, we could add a similar note in the vignette on available hooks.

**Comment by lorenzwalthert** [comment] 2020-01-08 15:42
optionally, I think `use-tidy-desc` should only write back to `DESCRIPTION` if it changes the `DESCRIPTION`. Because otherwise, If I understand the codemeta hook correctly, a new run of `codemetar::write_codemeta()` is required and the fileSize field will require a new commit all the time. Is that correct?

**Comment by maelle** [comment] 2020-01-08 15:46
yes that's correct!

**Comment by maelle** [comment] 2020-01-08 16:15
I wonder if the desc normalization suggestion should go to desc issue tracker.

**Comment by lorenzwalthert** [comment] 2020-01-08 16:34
> I wonder if the desc normalization suggestion should go to desc issue tracker.

I also just thought that. I can open an issue / PR.

**Comment by lorenzwalthert** [comment] 2020-01-08 22:11
This is the issue I opened: https://github.com/r-lib/usethis/issues/974. If they don't want to implement it, we can easily write our own `use_tidy_description()` with {desc} and implement the feature.

**Comment by maelle** [comment] 2020-01-15 08:56
Ok, thanks so nothing more to do?

**Closed** 2020-01-15 08:59 UTC
